"""empty message

Revision ID: 029545daf8cc
Revises: 244c69801908
Create Date: 2022-07-13 22:19:56.931377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029545daf8cc'
down_revision = '244c69801908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_constraint('user_accounts_username_key', 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('username', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_accounts_username_key', 'user_accounts', ['username'])
    op.drop_column('user_accounts', 'is_admin')
    # ### end Alembic commands ###
