"""empty message

Revision ID: 244c69801908
Revises: 920557078647
Create Date: 2022-07-13 22:03:31.295651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244c69801908'
down_revision = '920557078647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_accounts', 'job_position',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'job_position',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.drop_table('stock_list')
    # ### end Alembic commands ###
