"""empty message

Revision ID: 920557078647
Revises: 271dd4f44fd1
Create Date: 2022-07-13 19:42:59.313130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920557078647'
down_revision = '271dd4f44fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_accounts', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    # ### end Alembic commands ###
