"""empty message

Revision ID: d4572befd935
Revises: 
Create Date: 2022-07-12 21:33:05.244308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4572befd935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts')
    op.drop_table('job_positions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('position', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('user_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], name='job_positions_user_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_positions_pkey')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_accounts_pkey')
    )
    # ### end Alembic commands ###
