"""empty message

Revision ID: d519607a3c69
Revises: c4152d271d57
Create Date: 2022-07-15 09:55:23.854174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd519607a3c69'
down_revision = 'c4152d271d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('stocks_id', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('projects', 'stocks_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('stocks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'myarray')
    # ### end Alembic commands ###
